#!/usr/bin/env python3
"""Lines-of-code report for the XonoticGodot port.

Walks the port's source tree (src/, game/, tests/, tools/) and prints a
breakdown of files / code / comment / blank lines per area, classified with a
cloc-style C-family scanner (handles // and /* */ comments and string/char
literals so that URLs and `'/'` chars aren't miscounted as comments).

As a footnote it lists the line counts of the *original* Xonotic codebase the
port descends from: the DarkPlaces engine (C) and each QuakeC VM compiled by
gmqcc (server / client / menu, plus the QC code shared by all three). Those
numbers are pre-computed (see FOOTNOTE below) so the report stands alone even
without a Base/ checkout. Pass --base PATH to recompute them live and diff
against the baked-in baseline.

Usage:
    python tools/loc.py                 # port report + pre-computed Base footnote
    python tools/loc.py --base ../Base  # also recompute the Base numbers live
    python tools/loc.py --csv           # machine-readable rows for the port

The script lives in tools/ and assumes the port root is its parent directory.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass, field

# ---------------------------------------------------------------------------
# Pre-computed reference: original Xonotic "Base" line counts.
#
# Generated by running this script's counting core over Base/ on 2026-06-09
# (DarkPlaces .c/.h + qcsrc .qc/.qh/.inc). Regenerate with `--base <path>`.
# ---------------------------------------------------------------------------
FOOTNOTE = {
    # label: (files, code, comment, blank, total)
    "DarkPlaces engine (C/H)":   (243, 157378, 24640, 20428, 202446),
    "QCVM - server (SVQC)":      (174, 37784, 4340, 6203, 48327),
    "QCVM - client (CSQC)":      (109, 19989, 1449, 3085, 24523),
    "QCVM - menu (MenuQC)":      (340, 22328, 970, 2496, 25794),
    "QCVM - shared QC":          (1134, 113352, 11850, 17356, 142558),
}

CODE_EXTS = {".cs", ".c", ".h", ".gd", ".gdshader", ".gdshaderinc"}
QC_EXTS = {".qc", ".qh", ".inc"}
C_EXTS = {".c", ".h", ".cpp", ".cc", ".hpp", ".m"}

# Directory names pruned everywhere during a walk.
PRUNE_DIRS = {".git", ".godot", ".idea", ".vs", ".vscode", "obj", "bin",
              "node_modules", ".tmp", "build-obj"}


@dataclass
class Tally:
    files: int = 0
    code: int = 0
    comment: int = 0
    blank: int = 0
    total: int = 0

    def add_file(self, c: int, cm: int, b: int) -> None:
        self.files += 1
        self.code += c
        self.comment += cm
        self.blank += b
        self.total += c + cm + b

    def merge(self, other: "Tally") -> None:
        self.files += other.files
        self.code += other.code
        self.comment += other.comment
        self.blank += other.blank
        self.total += other.total

    def as_tuple(self):
        return (self.files, self.code, self.comment, self.blank, self.total)


def classify(text: str):
    """Return (code, comment, blank) line counts for C-family source text."""
    code = comment = blank = 0
    in_block = False
    for raw in text.splitlines():
        s = raw.strip()
        if not s:
            blank += 1
            continue
        has_code = False
        has_comment = False
        in_str = False
        quote = ""
        i, n = 0, len(s)
        while i < n:
            c = s[i]
            nxt = s[i + 1] if i + 1 < n else ""
            if in_block:
                has_comment = True
                if c == "*" and nxt == "/":
                    in_block = False
                    i += 2
                    continue
                i += 1
                continue
            if in_str:
                has_code = True
                if c == "\\":
                    i += 2
                    continue
                if c == quote:
                    in_str = False
                i += 1
                continue
            # plain code context
            if c == "/" and nxt == "/":
                has_comment = True
                break  # line comment: rest of line ignored
            if c == "/" and nxt == "*":
                has_comment = True
                in_block = True
                i += 2
                continue
            if c == '"' or c == "'":
                has_code = True
                in_str = True
                quote = c
                i += 1
                continue
            if not c.isspace():
                has_code = True
            i += 1
        if has_code:
            code += 1
        elif has_comment:
            comment += 1
        else:
            blank += 1
    return code, comment, blank


def count_file(path: str):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            return classify(fh.read())
    except OSError as exc:
        print(f"  ! skipped {path}: {exc}", file=sys.stderr)
        return (0, 0, 0)


def walk_count(root: str, exts: set[str], by_ext: dict[str, Tally] | None = None) -> Tally:
    """Count all files under root whose extension is in exts."""
    total = Tally()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in PRUNE_DIRS]
        for name in filenames:
            ext = os.path.splitext(name)[1].lower()
            if ext not in exts:
                continue
            c, cm, b = count_file(os.path.join(dirpath, name))
            total.add_file(c, cm, b)
            if by_ext is not None:
                by_ext.setdefault(ext, Tally()).add_file(c, cm, b)
    return total


# ---------------------------------------------------------------------------
# Reporting
# ---------------------------------------------------------------------------

def fmt(n: int) -> str:
    return f"{n:,}"


def row(label: str, t, width: int) -> str:
    files, code, comment, blank, total = t if isinstance(t, tuple) else t.as_tuple()
    return (f"  {label:<{width}}{fmt(files):>7}{fmt(code):>11}"
            f"{fmt(comment):>11}{fmt(blank):>9}{fmt(total):>11}")


def header(width: int) -> str:
    return (f"  {'':<{width}}{'files':>7}{'code':>11}"
            f"{'comment':>11}{'blank':>9}{'total':>11}")


def analyze_port(port_root: str):
    """Build the grouped port report. Returns (sections, grand)."""
    src = os.path.join(port_root, "src")
    sections = []  # (section_title, [(label, Tally), ...], section_total)

    # 1. Engine & shared libraries - one row per src/ project.
    lib_rows = []
    lib_total = Tally()
    if os.path.isdir(src):
        for proj in sorted(os.listdir(src)):
            pdir = os.path.join(src, proj)
            if not os.path.isdir(pdir):
                continue
            t = walk_count(pdir, CODE_EXTS)
            if t.files:
                lib_rows.append((proj, t))
                lib_total.merge(t)
    sections.append(("Engine & shared libraries  (src/)", lib_rows, lib_total))

    # 2. Godot game layer - game/ plus root-level .cs (Main.cs).
    game_rows = []
    game_total = Tally()
    game_dir = os.path.join(port_root, "game")
    if os.path.isdir(game_dir):
        for sub in sorted(os.listdir(game_dir)):
            spath = os.path.join(game_dir, sub)
            if os.path.isdir(spath):
                t = walk_count(spath, CODE_EXTS)
                if t.files:
                    game_rows.append((f"game/{sub}", t))
                    game_total.merge(t)
        # top-level .cs files directly inside game/
        top = Tally()
        for name in sorted(os.listdir(game_dir)):
            p = os.path.join(game_dir, name)
            if os.path.isfile(p) and os.path.splitext(name)[1].lower() in CODE_EXTS:
                top.add_file(*count_file(p))
        if top.files:
            game_rows.append(("game/ (root)", top))
            game_total.merge(top)
    # root-level .cs (Main.cs etc.)
    root_cs = Tally()
    for name in sorted(os.listdir(port_root)):
        p = os.path.join(port_root, name)
        if os.path.isfile(p) and os.path.splitext(name)[1].lower() in CODE_EXTS:
            root_cs.add_file(*count_file(p))
    if root_cs.files:
        game_rows.append(("(repo root)", root_cs))
        game_total.merge(root_cs)
    sections.append(("Godot game layer  (game/, Main.cs)", game_rows, game_total))

    # 3. Tests
    tests_dir = os.path.join(port_root, "tests")
    if os.path.isdir(tests_dir):
        t = walk_count(tests_dir, CODE_EXTS)
        sections.append(("Tests  (tests/)", [("tests/", t)], t))

    # 4. Tools (movement-ref C reference, etc.)
    tools_dir = os.path.join(port_root, "tools")
    if os.path.isdir(tools_dir):
        t = walk_count(tools_dir, CODE_EXTS)
        if t.files:
            sections.append(("Tools  (tools/)", [("tools/", t)], t))

    grand = Tally()
    for _, _, st in sections:
        grand.merge(st)
    return sections, grand


def print_report(port_root: str, base_path: str | None):
    sections, grand = analyze_port(port_root)
    width = 34

    print()
    print("=" * 80)
    print("  XonoticGodot - lines of code")
    print(f"  root: {os.path.abspath(port_root)}")
    print("=" * 80)

    for title, rows, stotal in sections:
        print()
        print(f"  {title}")
        print(header(width))
        print("  " + "-" * (width + 49 - 2))
        for label, t in rows:
            print(row(label, t, width))
        if len(rows) > 1:
            print("  " + "-" * (width + 49 - 2))
            print(row("subtotal", stotal, width))

    print()
    print("  " + "=" * (width + 49 - 2))
    print(row("TOTAL (port)", grand, width))
    print("  " + "=" * (width + 49 - 2))

    print_footnote(base_path, grand)


def print_footnote(base_path: str | None, port_grand: Tally):
    width = 34
    print()
    print("-" * 80)
    print('  [footnote] Original Xonotic "Base" line counts - what the port descends from')
    print("-" * 80)
    print()
    print("  The port replaces the DarkPlaces C engine and three gmqcc-compiled QuakeC")
    print("  virtual machines (server / client / menu, sharing a common QC library):")
    print()
    print(header(width))
    print("  " + "-" * (width + 49 - 2))

    live = compute_base(base_path) if base_path else None
    qcvm_total = Tally()
    base_total = Tally()
    for label, t in FOOTNOTE.items():
        tup = t
        print(row(label, tup, width))
        files, code, comment, blank, total = tup
        agg = Tally(files, code, comment, blank, total)
        base_total.merge(agg)
        if "QCVM" in label:
            qcvm_total.merge(agg)

    print("  " + "-" * (width + 49 - 2))
    print(row("all QuakeC (4 rows above)", qcvm_total, width))
    print(row("BASE TOTAL (engine + all QC)", base_total, width))
    print("  " + "=" * (width + 49 - 2))

    bc = base_total.code or 1
    print()
    print(f"  For scale: the port is currently {fmt(port_grand.code)} lines of code vs the")
    print(f"  original {fmt(base_total.code)} ({port_grand.code * 100 // bc}% of the engine+QC source it reimplements).")
    print("  Shared QC (common/ + lib/ + ecs/ + dpdefs/) is compiled into all three VMs,")
    print("  so it is counted once, not three times.")

    if live is not None:
        print()
        print("  [--base] live recount of", os.path.abspath(base_path) + ":")
        for label, t in live.items():
            baked = FOOTNOTE.get(label)
            flag = "" if baked == t.as_tuple() else "   <-- differs from baked-in baseline"
            print(row(label, t, width) + flag)


def compute_base(base_path: str) -> dict[str, Tally]:
    """Recompute the Base footnote numbers from a checkout."""
    dp = os.path.join(base_path, "darkplaces")
    qc = os.path.join(base_path, "data", "xonotic-data.pk3dir", "qcsrc")
    out: dict[str, Tally] = {}
    out["DarkPlaces engine (C/H)"] = walk_count(dp, C_EXTS)
    out["QCVM - server (SVQC)"] = walk_count(os.path.join(qc, "server"), QC_EXTS)
    out["QCVM - client (CSQC)"] = walk_count(os.path.join(qc, "client"), QC_EXTS)
    out["QCVM - menu (MenuQC)"] = walk_count(os.path.join(qc, "menu"), QC_EXTS)
    shared = Tally()
    for d in ("common", "lib", "ecs", "dpdefs"):
        shared.merge(walk_count(os.path.join(qc, d), QC_EXTS))
    out["QCVM - shared QC"] = shared
    return out


def print_csv(port_root: str):
    sections, grand = analyze_port(port_root)
    print("section,group,files,code,comment,blank,total")
    for title, rows, _ in sections:
        for label, t in rows:
            f, c, cm, b, tot = t.as_tuple()
            print(f"{title},{label},{f},{c},{cm},{b},{tot}")
    f, c, cm, b, tot = grand.as_tuple()
    print(f"TOTAL,port,{f},{c},{cm},{b},{tot}")


def main(argv):
    ap = argparse.ArgumentParser(description="Lines-of-code report for the XonoticGodot port.")
    ap.add_argument("--base", metavar="PATH",
                    help="path to a Xonotic Base/ checkout; recompute & diff the footnote")
    ap.add_argument("--csv", action="store_true", help="emit port rows as CSV")
    ap.add_argument("--root", metavar="PATH", default=None,
                    help="port root (default: parent of this script's tools/ dir)")
    args = ap.parse_args(argv)

    # Never let a legacy Windows console (cp1252) encoding crash or stall on output.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

    port_root = args.root or os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if not os.path.isdir(os.path.join(port_root, "src")):
        print(f"error: {port_root} does not look like the port root (no src/)", file=sys.stderr)
        return 1

    if args.csv:
        print_csv(port_root)
    else:
        print_report(port_root, args.base)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
